### ISSUE TITLE
NameError: name 'NO_HASH_ADDRESS_BALANCE' is not defined

### ISSUE THREAD

**Issue by Michael-Lyon** [ydaniels/django-cryptocurrency-payment#5]
* Django Cryptocurrency Payment version:
* Django version: 3.1
* Python version: 3.9
* Operating System:  linux parrot os

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did
I tried to make use of the tasks.update_payment_status()
```
Paste the command(s) you ran and the output.
Traceback (most recent call last):
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/michaellyon/flexvest/taskManager/run_tasks.py", line 54, in test3
    tasks.update_payment_status()
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/cryptocurrency_payment/tasks.py", line 16, in update_payment_status
    crypto_task.update_crypto_currency_payment_status()
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/cryptocurrency_payment/tasks.py", line 88, in update_crypto_currency_payment_status
    status, value = self.backend_obj.confirm_address_payment(
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/merchant_wallet/backends/btc.py", line 178, in confirm_address_payment
    return NO_HASH_ADDRESS_BALANCE, None
NameError: name 'NO_HASH_ADDRESS_BALANCE' is not defined
Job "test3 (trigger: interval[0:03:00], next run at: 2021-09-05 23:51:07 UTC)" raised an exception
Traceback (most recent call last):
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/home/michaellyon/flexvest/taskManager/run_tasks.py", line 54, in test3
    tasks.update_payment_status()
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/cryptocurrency_payment/tasks.py", line 16, in update_payment_status
    crypto_task.update_crypto_currency_payment_status()
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/cryptocurrency_payment/tasks.py", line 88, in update_crypto_currency_payment_status
    status, value = self.backend_obj.confirm_address_payment(
  File "/home/michaellyon/flexvest/env/lib/python3.9/site-packages/merchant_wallet/backends/btc.py", line 178, in confirm_address_payment
    return NO_HASH_ADDRESS_BALANCE, None
NameError: name 'NO_HASH_ADDRESS_BALANCE' is not defined
```

**Comment by ydaniels** [comment]
Yup found that, Thanks.  Run `pip install merchant-wallet --upgrade`

**Comment by Michael-Lyon** [comment]
Thanks. I'll do that.
